DELETE  http://localhost:3003/api/blogs/61b3e66d697f489cab272174
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhvbGFtdW5kbyIsImlkIjoiNjFiMDEzMzdjMDkyMzE5MjZmYTkzN2UwIiwiaWF0IjoxNjM5MjMyMjcxLCJleHAiOjE2MzkyMzU4NzF9.NuH7hkBFynrMscOECV-F5vd7pojF8n55a_R_feaIBu4